import type { LessonPayload } from '../types/presentation';

/**
 * Mock lesson payload — demo course (5 slides).
 * Timestamps & audio files generated by Google Cloud TTS (Neural2-F).
 */
export const mockLessonPayload: LessonPayload = {
  lessonId: 'demo-001',
  topicTitle: 'AI Tutor Slide Control Demo',
  status: 'ready',
  slides: [
    // ── Slide 0: Title ──────────────────────────────────────────────
    {
      id: 'slide-0',
      slideIndex: 0,
      audioUrl: '/audio/slide-0.mp3',
      audioDuration: 2.9,
      timepoints: [],
      transcript:
        "Welcome to the AI Tutor Slide Control Demo. Today, we will be testing how presentation APIs synchronize with text-to-speech for seamless LLM integration. Let's begin.",
      rawMarkdown: `# AI Tutor Slide Control Demo

Testing presentation APIs for LLM integration`,
    },

    // ── Slide 1: Fragment Examples ──────────────────────────────────
    {
      id: 'slide-1',
      slideIndex: 1,
      audioUrl: '/audio/slide-1.mp3',
      audioDuration: 2.7,
      timepoints: [
        { markName: 'frag-0', timeSeconds: 5.03, fragmentIndex: 0 },
        { markName: 'frag-1', timeSeconds: 7.04, fragmentIndex: 1 },
        { markName: 'frag-2', timeSeconds: 9.44, fragmentIndex: 2 },
      ],
      transcript:
        'Here are some fragment examples. These elements will appear one by one. Here is the first item. Followed by the second item. And finally, the third item.',
      rawMarkdown: `## Fragment Examples

These elements appear one by one:

- First item <!-- .element: class="fragment" -->
- Second item <!-- .element: class="fragment" -->
- Third item <!-- .element: class="fragment" -->`,
    },

    // ── Slide 2: Highlight Colors ───────────────────────────────────
    {
      id: 'slide-2',
      slideIndex: 2,
      audioUrl: '/audio/slide-2.mp3',
      audioDuration: 3.2,
      timepoints: [
        { markName: 'frag-0', timeSeconds: 6.85, fragmentIndex: 0 },
        { markName: 'frag-1', timeSeconds: 9.09, fragmentIndex: 1 },
        { markName: 'frag-2', timeSeconds: 11.93, fragmentIndex: 2 },
      ],
      transcript:
        'We can also dynamically change the colors of text to draw your attention. For instance, we can highlight text in red. Or, we can change it to green. And lastly, we can highlight it in blue.',
      rawMarkdown: `## Highlight Colors

Click "Next Fragment" to see highlights:

- Highlight RED <!-- .element: class="fragment highlight-red" -->
- Highlight GREEN <!-- .element: class="fragment highlight-green" -->
- Highlight BLUE <!-- .element: class="fragment highlight-blue" -->`,
    },

    // ── Slide 3: Digital Logic Example ──────────────────────────────
    {
      id: 'slide-3',
      slideIndex: 3,
      audioUrl: '/audio/slide-3.mp3',
      audioDuration: 4.8,
      timepoints: [
        { markName: 'frag-0', timeSeconds: 10.31, fragmentIndex: 0 },
        { markName: 'frag-1', timeSeconds: 15.46, fragmentIndex: 1 },
        { markName: 'frag-2', timeSeconds: 18.15, fragmentIndex: 2 },
      ],
      transcript:
        "Let's look at a practical application with a digital logic example. Consider a 4 to 1 Multiplexer. So, consider the select line values 0 and 1, which are S1 and S0. This combination will select the first input, I zero, and route it directly to the output Y.",
      rawMarkdown: `## Digital Logic Example

Consider a **4:1 Multiplexer**:

Select lines: **S1** <!-- .element: class="fragment highlight-red" data-fragment-index="1" --> and **S0** <!-- .element: class="fragment highlight-red" data-fragment-index="1" -->

Inputs: **I0** <!-- .element: class="fragment highlight-blue" data-fragment-index="2" -->, **I1** <!-- .element: class="fragment highlight-blue" data-fragment-index="2" -->, **I2** <!-- .element: class="fragment highlight-blue" data-fragment-index="2" -->, **I3** <!-- .element: class="fragment highlight-blue" data-fragment-index="2" -->

Output: **Y** <!-- .element: class="fragment highlight-green" data-fragment-index="3" -->`,
    },

    // ── Slide 4: End of Demo ────────────────────────────────────────
    {
      id: 'slide-4',
      slideIndex: 4,
      audioUrl: '/audio/slide-4.mp3',
      audioDuration: 2.5,
      timepoints: [],
      transcript:
        'And that brings us to the end of the demo! All fragment and highlight types have been successfully demonstrated. Your architecture is now officially ready for LLM integration.',
      rawMarkdown: `## End of Demo

All fragment and highlight types demonstrated!

🎓 Ready for LLM integration`,
    },
  ],

  // ── Course Plan (matches the actual demo slides) ──
  coursePlan: {
    courseTitle: 'AI Tutor Slide Control Demo',
    chapters: [
      {
        id: 'ch-1',
        title: 'Slide Control Demo',
        topics: [
          { id: 't-intro', title: 'Introduction', slideIndices: [0] },
          {
            id: 't-fragments',
            title: 'Fragment & Animation System',
            slideIndices: [1, 2],
            children: [
              { id: 't-frag-examples', title: 'Fragment Examples', slideIndices: [1] },
              { id: 't-highlight', title: 'Highlight Colors', slideIndices: [2] },
            ],
          },
          {
            id: 't-digital-logic',
            title: 'Digital Logic Example',
            slideIndices: [3],
          },
          { id: 't-summary', title: 'Summary & Next Steps', slideIndices: [4] },
        ],
      },
    ],
  },

  currentPosition: {
    chapterIndex: 0,
    topicPath: [1, 0],
  },
};
